From php:7.4-apache
RUN apt-get update && \
    apt-get install -y unzip libzip-dev zlib1g-dev
RUN docker-php-ext-install mysqli
RUN docker-php-ext-install zip
RUN mv "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/php.ini"
RUN sed -i 's/;\(session.save_path\)/\1/g' "$PHP_INI_DIR/php.ini"

CMD ["apache2-foreground"]